export const settingNameMap = {
  Brightness: "亮度",
  Contrast: "对比度",
  Hue: '色调',
  Saturation: "饱和度",
  Sharpness: "锐度",
  Gamma: "伽马",
  ColorEnable: '启用颜色',
  WhiteBalance: "白平衡",
  BacklightCompensation: "背光补偿",
  Gain: "增益",
  Pan: "水平",
  Tilt: "垂直",
  Roll: "旋转",
  Zoom: "缩放",
  Exposure: "曝光",
  Iris: "光圈",
  Focus: "聚焦",
};
